name: bac_helper_sc
description: "a productivity app that help bac students to preprare for the exam"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  smooth_page_indicator: ^1.1.0
  flutter_svg: ^2.0.7
  iconsax: ^0.0.8
  flutter_screenutil: ^5.9.0
  provider: ^6.1.2

  flutter:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Rubik-Black.ttf
          weight: 900

  assets:
    - assets/images/

  uses-material-design: true

